#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

cookbook "apache2"
cookbook "apt"
cookbook "ark"
cookbook "bash",
  :git => "https://github.com/myplanetdigital/chef-bash.git",
  # PR: https://github.com/mszoernyi/chef-bash/pull/1
  :ref => "feature/bash_profile-resource"
cookbook "chef-solo-search",
  :git => "https://github.com/edelight/chef-solo-search.git",
  :ref => "0.4.0"
cookbook "drush",
  :git => "https://github.com/msonnabaum/chef-drush.git"
cookbook "fail2ban"
cookbook "git"
cookbook "jenkins",
  :git => "https://github.com/opscode-cookbooks/jenkins.git"
cookbook "jenkins-job-builder",
  # Pending PR: https://github.com/needle-cookbooks/chef-jenkins-job-builder/pull/1
  :git => "https://github.com/myplanetdigital/chef-jenkins-job-builder.git",
  :ref => "1-python26-support"
cookbook "oh-my-zsh"
cookbook "openssh"
cookbook "php"
cookbook "phpcs",
  :git => "https://github.com/myplanetdigital/chef-phpcs.git"
cookbook "phpunit",
  :git => "https://github.com/msonnabaum/chef-phpunit.git"
cookbook "postfix"
cookbook "python",
  # Pending PR: https://github.com/opscode-cookbooks/python/pull/49
  :git => "https://github.com/myplanetdigital/python.git",
  :ref => "COOK-3335-unset-version-unless-source"
cookbook "sudo"
cookbook "user",
  :git => "https://github.com/myplanetdigital/chef-user.git",
  # https://github.com/fnichol/chef-user/pull/23
  :ref => "23-plaintext-pwd"
cookbook "vim"
cookbook "xdebug",
  :git => "https://github.com/myplanetdigital/chef-xdebug.git",
  :ref => "create-logfile"
cookbook "xserver",
  :git => "https://github.com/travis-ci/travis-cookbooks.git",
  :path => "ci_environment/xserver"
cookbook "zsh"
