#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

cookbook "apache2"
cookbook "apt"
cookbook "chef-solo-search",
  :git => "https://github.com/myplanetdigital/chef-solo-search.git"
cookbook "drush",
  :git => "https://github.com/msonnabaum/chef-drush.git",
  :ref => "master"
cookbook "git"
cookbook "jenkins",
  :git => "https://github.com/myplanetdigital/chef-jenkins.git",
  :ref => "GH-11-basic-auth-opt"
cookbook "oh-my-zsh"
cookbook "postfix"
cookbook "php"
cookbook "phpunit",
  :git => "https://github.com/myplanetdigital/chef-phpunit.git",
  :ref => "GH-7-version-attr"
cookbook "sudo"
cookbook "user",
  :git => "https://github.com/myplanetdigital/chef-user.git",
  # https://github.com/fnichol/chef-user/pull/23
  :ref = > "23-plaintext-pwd"
cookbook "vim"
cookbook "xdebug",
  :git => "https://github.com/myplanetdigital/chef-xdebug.git",
  :ref => "create-logfile"
cookbook "zsh"
